<a href="https://colab.research.google.com/github/gnasche-2003/thuchanhtoancp/blob/main/Ch%C6%B0%C6%A1ng_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chương 5


#Thực hành 1: Lặp để tìm nghiệm

In [1]:
x = 3
print(x)

3


In [2]:
import math
x = math.sqrt(1+x)
print(x)

2.0


In [4]:
import math
x = math.sqrt(1+x)
print(x)

1.7320508075688772


In [5]:
import math
x = math.sqrt(1+x)
print(x)

1.6528916502810695


In [6]:
import math
x = math.sqrt(x)
print(x)

1.2856483384973783


#Thực hành 2: Lặp trình whlie để tìm nghiệm


In [7]:
import math
x = 3
lap = 1
while (x != math.sqrt(x + 1)):
  x = math.sqrt(x + 1)
  lap += 1
x

1.618033988749895

In [8]:
lap 

32

#Thực hành 3: Giải phương trình bằng hàm solve trong sympy


In [11]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1 + x), x)

[1/2 + sqrt(5)/2]

#Thực hành 4:Các phép toán trên vector


In [12]:
import numpy as np
v1 = np.array([1.,2.,3.]) # tao vector 3 chieu
v2 = np.array([2.,1.,0.])
v3 = v1 + v2 # cong vector
v3

array([3., 3., 3.])

Thực hiện phép toán trên vector

In [13]:
3*v1 + 2*v2

array([7., 8., 9.])

So sánh numpy.array với list trong python

In [14]:
[1,2,3] + [2,1,0]

[1, 2, 3, 2, 1, 0]

In [15]:
3*[1,2,3] + 2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

Ghép nối(Concatenating) 2 hoặc nhiều vector

In [19]:
v4 = np.hstack([v1, v2])
v4

array([1., 2., 3., 2., 1., 0.])

Phép nhân vô hướng 2 vector:


In [21]:
np.dot(v1,v2)

4.0

Tính toán giá trị sin của vector

In [22]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [23]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

Hàm xử lý sin trong gói sympy sẽ không hỗ trợ tính toán toàn bộ vector chứa dữ liêu

In [24]:
import sympy as sy
sy.sin(angles)

AttributeError: ignored

TypeError: unhashable type:"numpy.ndarray"

Chương trình lặp vector mới được xây dựng sẵn tạm thời:


In [25]:
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2, 5)
sinangle = np.zeros(5)   #tuong duong sinangle = np.array([0.0, 0.0, 0.0, 0.0, 0.0])
len(angles) #kiem tra kich thuoc/ so chieu cua vector angles.
for i in range(len(angles)):
  sinangle[i] = sysin(angles[i])    #luu y: o day phai enter 2 lan de thoat khoi vong lap for
sinangle

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

#Thực hành 5: Tính tổng các tích giữa ma trận và vector. Gỉa định gói thư viện numpy được đưa vào hê thống có tên là np. Dạng:

In [26]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)], [np.sin(goc), np.cos(goc)] ])
V = np.array([1., 0.])
Y = np.dot(A, V)
Y

array([0.5      , 0.8660254])

#Thực hành 6: Tính toán đạo hàm trên 1 vector dữ liệu


+Trường hợp dx cố định:


In [29]:
from numpy import diff
dx = 0.1
y = [1, 2, 3, 4, 4, 5, 6]
dy = diff(y)/dx
dy

array([10., 10., 10.,  0., 10., 10.])

In [28]:
z = np.array([1,2,3,4,4,5,6])
dz = diff(z)/dx
dz

array([10., 10., 10.,  0., 10., 10.])